### ISSUE TITLE
Variables lesson only teaches $^ but refers to $<

### ISSUE THREAD

**Issue by noamross** [swcarpentry/make-novice#1]
The [variables lesson](https://github.com/swcarpentry/make-novice/blob/gh-pages/03-variables.md) teaches the `$^` variable, but I see the `$<` variable is in the exercise, though it is never mentioned.  I also see that `$<` is used in the next (dependencies) lesson.

**Comment by beroe** [comment]
Plus one to this.

**Comment by mikej888** [comment]
It is defined in the exercise itself:

> ...$<, which means 'the first dependency of the current rule'.

But this can be made clearer. Something like, "For this exercise you will also need another automatic variable, $<, which means 'the first dependency of the current rule' ?

I was trying to avoid introducing it by an example explicitly as some attendees complained that some of the exercises were too much of the copy-paste-customise approach.
