### ISSUE TITLE
Add Python version statement

### ISSUE THREAD

**Issue by mfoos** [swcarpentry/make-novice#102]
I take it from the existing issue of translating this lesson to bash that I'm not the only one visiting this lesson "out of order" (that is, part of a workflow that doesn't start with a Python lesson). It's not easy for me to find the information about whether this lesson runs equally well in Python 2 AND 3 - do maintainers think that would be helpful to add?

**Comment by gcapes** [comment]
Thanks for the idea - I've just tested the scripts using python2 and they work fine for me. I usually use python3. I'll add that to the setup info.
