### ISSUE TITLE
MatplotlibDeprecationWarning when using Python 3.6

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/make-novice#119]
```
python plotcount.py isles.dat ascii
```
Threw a

```
/anaconda3/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py:106: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  warnings.warn(message, mplDeprecation, stacklevel=1)
```

Not sure whether this needs to be fixed or mentioned in the Instructor Notes.

**Comment by gcapes** [comment]
Thanks @lexnederbragt 
I'll have a look into this in a couple of days. I guess it would be better to fix the python code so it doesn't give a warning.

**Comment by gcapes** [comment]
A reminder for me as something to follow when investigating:
https://stackoverflow.com/questions/46933824/matplotlib-adding-an-axes-using-the-same-arguments-as-a-previous-axes
