### ISSUE TITLE
Use language-make for syntax highlighting of source code

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/make-novice#134]
I tried this, but it displays a red box around some of the code - do you know why @rgaiacs?

![image](https://user-images.githubusercontent.com/12446270/40178698-24240d3c-59da-11e8-80ab-def71e1889e1.png)

**Comment by rgaiacs** [comment]
```
        python testzipf.py abyss.dat isles.dat last.dat > results.txt
```

has spaces at the begin of the line but Make requires a tab. If you fix this the red box is disappear.

**Comment by gcapes** [comment]
Great, thanks!

**Comment by gcapes** [comment]
Thoughts on this @rgaiacs? The syntax is correct this time.
I could use `. language-bash` instead for this code block to avoid the red boxes, but that's not the correct language.

![image](https://user-images.githubusercontent.com/12446270/40227467-7fa088aa-5a86-11e8-9911-e74f2ff353fe.png)

**Comment by rgaiacs** [comment]
> The syntax is correct this time.

I get the felling that `include` isn't included in rouge's rules, https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/make.rb

**Comment by gcapes** [comment]
What would you recommend? Just leave the Make lesson using the new `language-make` option and submit an issue to rouge?

**Comment by gcapes** [comment]
There's too many instances (IMO) where this appears for `language-shell` to be a satisfactory solution - the syntax highlighting of the makefile would change between instances, so I think I'll use the new highlighting and put up with the red boxes until there is a fix from rouge.

Example from episode 7
![image](https://user-images.githubusercontent.com/12446270/40235040-d3eda1b2-5aa0-11e8-95df-19cdbf936999.png)

**Comment by gcapes** [comment]
Issue now open at https://github.com/jneen/rouge/issues/913
