### ISSUE TITLE
Need plotcounts.py in fig/09-conclusion-challenge-1.png

### ISSUE THREAD

**Issue by fraserphysics** [swcarpentry/make-novice#137]
The figure fig/09-conclusion-challenge-1.png has "plotcount.py" second row on the left.  The file is called "plotcounts.py" now.

I later also noticed that the figure uses the names wordcount.py and zipf_test.py, but the code now uses the names countwords.py and testzipf.py.

I looked around, but did not find out how one makes the figures.  How does one make these figures?

**Comment by gcapes** [comment]
Well spotted! Thanks. I'm happy to update the figures, but if you'd like to (?) the guide is near the bottom here: http://swcarpentry.github.io/make-novice/guide/

**Comment by gcapes** [comment]
I started checking if I'd missed the name update anywhere else and have made the figures now. Hopefully I've not missed it anywhere else now!
