### ISSUE TITLE
[bug] plotcounts.py uses deprecated syntax (and will stop working in Py 3.8)

### ISSUE THREAD

**Issue by krishnakumarg1984** [swcarpentry/make-novice#151]
When the file `plotcounts.py` is executed with the latest python interpreter `3.7.3`, it gives a warning 

>plotcounts.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working  
`from collections import sequence`

Can this python file be updated so as to prevent imminent breakage of this lesson for new learners?

**Comment by gcapes** [comment]
Great, thanks for reporting this. This was nearly fixed in #148 -- it's just that the zip file needs updating too which was overlooked. I'll do that now.
