### ISSUE TITLE
[Question] How are the png files for the DAGs in the lessons generated?

### ISSUE THREAD

**Issue by krishnakumarg1984** [swcarpentry/make-novice#152]
In the spirit of self-documentation, it would be great to visualise our makefiles as Directed Acyclic Graphs (DAGs). The lessons have up-to-date png images that visualize the dependencies coded within the makefile. How were these generated? Can this script be shared with students?

**Comment by gcapes** [comment]
Hi,
They were created using `makefile2graph`. See http://swcarpentry.github.io/make-novice/guide/#makefile-dependency-images

I can see pros and cons to suggesting learners install it and use it on their makefiles. If you teach the lesson and use it, perhaps you let me know how it went?
Thanks

**Comment by krishnakumarg1984** [comment]
@gcapes Thank you for your reply. 

I tried using `makefile2graph`, however it err

**Comment by gcapes** [comment]
Hi @krishnakumarg1984 

I just downloaded it having installed the prerequisites, and ran `make diagrams` in the root directory of this repo. Worked fine.

How are you trying to run the tool?
