### ISSUE TITLE
Add a remark about difference between gmake vs make (e.g. on AIX systems)

### ISSUE THREAD

**Issue by mcytowski** [swcarpentry/make-novice#153]
Hi all,
on some UNIX based systems (e.g. AIX) by default "make" command does not point to GNUmake and "gmake" needs to be used for GNUmake Makefiles. Would it make sense to add a short notice/remark about that somewhere around the Introduction section and paragraph "GNU Make is a free, fast, well-documented, and very popular Make implementation. From now on, we will focus on it, and when we say Make, we mean GNU Make."
Regards,
Maciej

**Comment by gcapes** [comment]
Hi @mcytowski 

Do you think this is a common scenario? I had to look up what AIX is :)

If this is something that most learners wouldn't encounter (which is my suspicion) then I think that the *instructor notes* section in extras would the appropriate place for it.

**Comment by mcytowski** [comment]
Hi @gcapes 
you are probably right, this is not a very common scenario. However, as a trainer I had to include it in my training materials for the users of one of the HPC systems. 
Thanks for the suggestion, I will propose this small remark as an addition to instructor notes. Probably a remark that GNUmake is sometimes available as gmake rather than make is sufficient.
