### ISSUE TITLE
Danger: remove with wildcard

### ISSUE THREAD

**Issue by tautme** [swcarpentry/make-novice#163]
What do you think about not using wildcards with the remove command?

In the second section **Makefiles**, the learner is asked to enter 

`rm *.dat *.png`

I accidental entered:

`rm *.dat * .png`

[02-makefiles.md](https://github.com/swcarpentry/make-novice/edit/gh-pages/_episodes/02-makefiles.md)

**Comment by gcapes** [comment]
Thanks for the issue. What would you propose instead of using wildcards?
