### ISSUE TITLE
Are Make functions really "novice" material ?

### ISSUE THREAD

**Issue by mboisson** [swcarpentry/make-novice#21]
The syntax of Make functions is often obscure and is hardly readable. Is this really "novice" material ?

I do not have a strong opinion. Any opinion from someone who gave this class ?

**Comment by lexnederbragt** [comment]
I think it is more a lesson for novices at make, than for novices in general. The prerequisites clearly state "Some previous experience with using the shell to list directories, create, copy, remove and list files and directories, and run simple scripts is necessary".

There is definitely room for an intermediate make lesson (i.e., teaching more advanced make).

**Comment by mikej888** [comment]
The shell functions come at the end and can be dropped by instructors if they judge it to be beyond their audience. In the first two runs of the first version of this lesson (back in 2012) they weren't mentioned. However, I found I had to mention them anyway to answer student questions relating to 03-variables.md which has:

> We get:
> make: *** No rule to make target `*.dat', needed by `analysis.tar.gz'.  Stop.
> As there are no files that match the pattern *.dat the name *.dat is used as a file name itself, and 
> there is no file matching that, nor any rule so we get an error. We need to explicitly rebuild the .dat 
> files first:
>
> $ make dats
> $ make analysis.tar.gz

And which gave rise to questions relating to automatically determining the .dat file names from the .txt file names.
