### ISSUE TITLE
Version control make-lesson/ data directory

### ISSUE THREAD

**Issue by bsmith89** [swcarpentry/make-novice#36]
Changes to this lesson may sometimes require corresponding changes to the "data directory"
`make-lesson`.  This directory is currently saved to the repository as a ZIP file which makes it easy for learners to download the one file and unpack it on their own computers.  However, this also means
that changes to the lesson which involve a modified content of `make-lesson/` now require updating
a large binary blob.

I'm not entirely familiar with how lesson maintainers keep the compiled lesson up-to-date with the
markdown source when merging changes, but could we treat the data directory similarly?

My first inclination would be to add an uncompressed version of the directory to the repository and
incorporate a recipe into `Makefile` which compresses this directory at the same time as the HTML output is compiled.

This way, I can edit the lesson and `plotwords.py` in a single commit, if I so desire.

What are the problems with this approach that I'm not considering?

I'm ready to submit a pull-request if this is the right way to do things.

**Comment by bsmith89** [comment]
Oh, I see it now.  This already happens from the `code/` and `data/` directories.

My bad.  I should have looked more closely at the Makefile.

**Comment by mikej888** [comment]
No worries :-)
