### ISSUE TITLE
Pull material from Byron Smith

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/make-novice#40]
https://bsmith89.github.io/make-bml/

**Comment by mikej888** [comment]
Sections https://bsmith89.github.io/make-bml/#directory-structure and https://bsmith89.github.io/make-bml/#file-naming would be good as new sections after the current content.
The challenge in 08-conclusion.md would need come before this and the conclusion text itself afterwards.

**Comment by mikej888** [comment]
Previous commits related to this issue:

* 8a4f5f45ecf832637077123e7ac1e5a65652d3e9: Merge pull request #42 from mikej888/bsmith.
* 59ec9b706fd85d3e9dd8d63870171b5e3268d91b: Small rephrasings from Byron Smith's lesson

**Comment by mikej888** [comment]
Commits related to this issue:


* ed86c15aa4cd3c9a9f15931493fdca9bf954128f: Added 'Adding the Makefile to our archive' challenge.
* 12725c9ab407eec06a1c86bd84901d33011a573b: Added exercise to create .tar.gz archive of all code, data, plots and summary table.
* 66b6ee7194cd36c3f822c17c1722b641dd775ae1: Added ASCII visualisation from plotcount.py.
* 1dfbc153fcc5f788c5f128d3b3f2909b102e6773: Added ASCII visualisation from plotcount.py.
* ea42f952e44123342a6b9534c404d0dc4ce92bb7: Added text on line continuation character to reference.md.
* 0416bfbd00df23a157f7bce2d3f65b821b2c7f5d: Updated to explain that pattern rule works no matter what stem is being matched.
* b6d143c5e7f6a50f00a95fdcb9cc750e9ab0d888: Extended TAB description.
