### ISSUE TITLE
List complete makefile at several points during the lesson

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/make-novice#5]
I really like the lesson!

One thing that would help the students, especially those working through the material on their own, would be occasionally list the entire makefile as it is at that point in the lesson. I'd be happy to put that in a pull request.

**Comment by mikej888** [comment]
Yes, that would be good, thanks. I provided the snapshots in code/samples/ for this reason, but those were more for instructors to give out to students to ensure they were all in-synch.

**Comment by mikej888** [comment]
Merged #9
