### ISSUE TITLE
error in plotcount

### ISSUE THREAD

**Issue by bheavner** [swcarpentry/make-novice#51]
$ python plotcount.py isles.dat ascii

Traceback (most recent call last):
  File "plotcount.py", line 94, in <module>
    truncate=False):
  File "plotcount.py", line 77, in plot_ascii_bars
    truncate=truncate)
  File "plotcount.py", line 59, in get_ascii_bars
    biggest_bar = symbol * round(maxlen / len(symbol))
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by bheavner** [comment]
Not sure if useful, but I'm using a mac, and:
$ python --version
Python 2.7.10

**Comment by gcapes** [comment]
I aim to look at this over the next few days. For what it's worth, I was thinking of removing the ascii diagrams anyway as I don't think they add anything to the lesson. Do the "normal" plots work for you?

**Comment by bheavner** [comment]
The png plots work for me...

**Comment by isaacye** [comment]
I ran into the same 'TypeError' and it might be simply corrected by

biggest_bar = symbol * int(round(maxlen / len(symbol)))

**Comment by gcapes** [comment]
That didn't correct the error for me @isaacye  I'm afraid. I've little experience with python but will take this as an opportunity to look into it as time allows.

**Comment by gcapes** [comment]
I've now got an ascii plot but the values are only non-zero for the first line. Leave it with me.

**Comment by gcapes** [comment]
Please could you check this works for you before I push the commit:

def get_ascii_bars(values, truncate=True, maxlen=10, symbol='#'):
    """
    Given a list of values, create a list of strings of symbols, where each
    strings contains N symbols where N = ()(value / minimum) /
    (maximum - minimum)) * (maxlen / len(symbol)).
    """
    maximum = max(values)
    if truncate:
        minimum = min(values) - 1
    else:
        minimum = 0
    # Conversion to floats is required for compatibility with python 2, because
    # it doesn't do integer division correctly
    value_range=float(maximum - minimum)
    prop_values = [(float(value - minimum) / value_range) for value in values]
    biggest_bar = symbol * int(round(maxlen / len(symbol)))
    bars = [biggest_bar[:int(round(prop * len(biggest_bar)))]
            for prop in prop_values]
    return bars

**Comment by gcapes** [comment]
If someone using Python 3 could also test that I've not broken things for them, that would be great! @gvwilson maybe?
