### ISSUE TITLE
Provide solution for final activity - Creating an Archive

### ISSUE THREAD

**Issue by bheavner** [swcarpentry/make-novice#54]
I've got a working solution, but am sure there's a much nicer way. Here's what I did:

```
include config.mk

ARCHIVE_DIR=zipf_analysis
TXT_FILES=$(wildcard books/*.txt)
DAT_FILES=$(patsubst books/%.txt, %.dat, $(TXT_FILES))
PNG_FILES=$(patsubst books/%.txt, %.png, $(TXT_FILES))
FILE_LIST=$(TXT_FILES) $(DAT_FILES) $(PNG_FILES) $(COUNT_SRC) $(ZIPF_SRC) $(PLOT_SRC) results.txt Makefile config.mk

## archive     : create an archive containing all code, data, plots, and summary table
.PHONY : archive
archive : results.txt $(PNG_FILES)
        mkdir -p $(ARCHIVE_DIR)
        cp $(FILE_LIST) $(ARCHIVE_DIR)
        tar -czf zipf_analysis.tar.gz $(ARCHIVE_DIR)

## all         : Generate Zipf summary table and plots of word counts.
.PHONY : all
all : results.txt $(PNG_FILES)

## results.txt : Generate Zipf summary table.
results.txt : $(DAT_FILES) $(ZIPF_SRC)
        $(ZIPF_EXE) *.dat > $@

## dats        : Count words in text files.
.PHONY : dats
dats : $(DAT_FILES)

%.dat : books/%.txt $(COUNT_SRC)
        $(COUNT_EXE) $< $*.dat

## pngs        : Plot word counts.
.PHONY : pngs
pngs : $(PNG_FILES)

%.png : %.dat $(PLOT_SRC)
        @echo $(PLOT_EXE) $*.dat $*.png
        $(PLOT_EXE) $*.dat $*.png

## clean       : Remove auto-generated files.
.PHONY : clean
clean : 
        rm -f $(DAT_FILES) $(PNG_FILES) results.txt
        rm -rf $(ARCHIVE_DIR)

## variables   : Print variables.
.PHONY: variables
variables:
        @echo TXT_FILES: $(TXT_FILES)
        @echo DAT_FILES: $(DAT_FILES)
        @echo PNG_FILES: $(PNG_FILES)

.PHONY: help
help : Makefile
        @sed -n 's/^##//p' $<
```

**Comment by gcapes** [comment]
The solutions look to have got lost during the lesson template revamp. Here is the solution which existed before the template update:
http://gcapes.github.io/make-novice/solutions.html

I aim to dedicate some time to this lesson over the next couple of weeks.
Thanks

**Comment by bheavner** [comment]
That solution doesn't seem to include the "create an archive containing all code, data, plots, and summary table" instruction on the last exercise, though. (and thanks for your work!)

**Comment by gcapes** [comment]
Hi @bheavner, 
Thanks for your solution. I'm not sure that I would change much in your file other than to move the `archive` target below `all`, so that `all` remains the default. I'll also add the `FILE_LIST` variable to the `variables` rule. With a lack of alternative suggestions forthcoming, I'll add this as the solution.
....
In the process of doing so, I've found the solution was there in the repo all along, just not linked to from the lesson, due to a formatting error. It's got several improvements on top of my suggestions above.
