### ISSUE TITLE
Minor format change suggestion

### ISSUE THREAD

**Issue by isaacye** [swcarpentry/make-novice#55]
It might be better to use 'bold' or 'italic' to say 'Make' is the 'Make'.

"Make was developed by Stuart Feldman in 1977 as a Bell Labs summer intern, and remains in widespread use today. Make can execute the commands needed to run our analysis and plot our results. Like shell scripts it allows us to execute complex sequences of commands via a single shell command. Unlike shell scripts it explicitly records the dependencies between files - what files are needed to create what other files - and so can determine when to recreate our data files or image files, if our text files change. Make can be used for any commands that follow the general pattern of processing files to create new files, for example::"

**Comment by gcapes** [comment]
Not a bad suggestion! A pull request would be welcome. Otherwise I'll probably get to it next week.

**Comment by gcapes** [comment]
I've been reviewing the lesson recently and Make is always referred to using a capital letter in the text. Given this is a lesson on Make, I think the meaning is clear enough. If there are instances where you think the text needs clarification, please let me know by re-opening this issue  and I'll review the decision.
Thanks again for your input!
