### ISSUE TITLE
Instructions for installing make

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/make-novice#58]
I am setting up a website for a one-day workshop to teach this lesson, but can't find any instructions for installing `make`. I am uncertain whether `make` maybe is installed when learners follow the bash shell installation instructions, and/or whether it is complicated to install on some versions of operating systems. Alternatively, we will do it as first thing of the workshop. Any suggestions/experiences?

**Comment by gcapes** [comment]
What OS are you going to be running this on? You can check if make is already installed by entering `make -v` into a terminal. For me this returns `GNU Make 3.81`

**Comment by lexnederbragt** [comment]
My learners can be on any OS that we normally have at workshops. Personally, I run MAC OS X with make 3.81.

**Comment by gcapes** [comment]
Did you find the answer to this?

**Comment by lexnederbragt** [comment]
Sort of. See http://lists.software-carpentry.org/pipermail/discuss/2016-October/004819.html
