### ISSUE TITLE
Use of $* in 05-patterns

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/make-novice#71]
In 05-patterns, the `dat` rule uses `$*`:

> `%.dat : books/%.txt wordcount.py`
>`        python wordcount.py $< $*.dat`

It could have used `$@` instead, which is probably even better. I suspect `$*` is used because it is important to teach it, and this is a good place for that. But if this is the reason, perhaps the lesson should explain that `$@` could have been used here as well?

**Comment by gcapes** [comment]
Thanks Lex. I would think the reason is as you described: to introduce `$*`. I've now added a short comment at the end of this lesson to address this observation. 
Cheers
