### ISSUE TITLE
Add instructions for obtaining .txt and .py files mentioned in Introduction

### ISSUE THREAD

**Issue by maherou** [swcarpentry/make-novice#80]
The introduction of this lesson ([Automation and Make](http://swcarpentry.github.io/make-novice/01-intro/)) starts discussion by listing the text files and Python scripts used in the examples on the same page:

|- books
|  |- abyss.txt
|  |- isles.txt
|  |- last.txt
|  |- LICENSE_TEXTS.md
|  |- sierra.txt
|- plotcount.py
|- wordcount.py
|- zipf_test.py

However, there are no instructions for how to obtain these files.  I can see that the Python files are in the `make-novice/code` folder, and the text files are in `make-novice/data/books` but I don't know how to access them on my local machine.  

Perhaps instructions are given elsewhere, but to a new student who is wanting to learn about `make` independent from other content, it would be good to include some instructions on this page.

**Comment by gcapes** [comment]
Thanks for this comment. This confused me too (#55). The files can be obtained via the [setup tab](http://swcarpentry.github.io/make-novice/setup/).

I never got round to adding a link from the main page. I'll do that now. There isn't a consistent approach to this in the other lessons. The [python](http://swcarpentry.github.io/python-novice-inflammation/) lesson has a "Getting started" section, but it's not very prominent. The shell and R lessons don't mention the setup instructions.

Perhaps we should have a "set up" box in each of the lessons? I'll ask for input via the list.

**Comment by tracykteal** [comment]
This is also being discussed more generally for consistency across all lessons at https://github.com/swcarpentry/styles/issues/97
