### ISSUE TITLE
Use automatic variables instead of $* in 09 challenges?

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/make-novice#92]
In episode 6 we remark that

> This episode has introduced pattern rules, and used the $* variable in the dat rule in order to explain how to use it. Arguably, a neater solution would have been to use $@ to refer to the target of the current rule (see below), but then we wouldn’t have learned about $*.
> ```
> %.dat : books/%.txt wordcount.py
>       python wordcount.py $< $@
>```

However, the solutions to the exercises in episode 9 use `$*` in the png rule. 
> ```
> %.png : %.dat $(PLOT_SRC)
> 	$(PLOT_EXE) $*.dat $*.png
> ```
Is there a reason not to change the solution to use the (more intuitive) automatic variables?
> ```
> %.png : %.dat $(PNG_SRC)
>	$(PNG_EXE) $< $@
> ```

**Comment by gcapes** [comment]
@mikej888

**Comment by mikej888** [comment]
Agreed, see #93
