### ISSUE TITLE
UnicodeDecodeError when processing books/last.txt with Python 3 and vanilla shell environment on Arch Linux

### ISSUE THREAD

**Issue by bast** [swcarpentry/make-novice#99]
When processing books/last.txt with Python 3 and vanilla shell environment on Arch Linux I get (this happened to me as participant of a lesson given by @lexnederbragt ):
```
$ python wordcount.py books/last.txt last.dat

Traceback (most recent call last):
  File "wordcount.py", line 131, in <module>
    word_count(input_file, output_file, min_length)
  File "wordcount.py", line 118, in word_count
    lines = load_text(input_file)
  File "wordcount.py", line 14, in load_text
    lines = input_fd.read().splitlines()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6862: ordinal not in range(128)
```

I know how to avoid this:
```
$ export LC_ALL=en_US.UTF-8
$ export LANG=en_US.UTF-8
$ export LANGUAGE=en_US.UTF-8
```

And I can submit a PR for that.

However, I would recommend to update the book example to only contain text that can be encoded with ASCII to avoid any such trouble in the class room since character encoding is not the point of this exercise.

What solution do the maintainers of this lesson prefer?

**Comment by gcapes** [comment]
Hi, and thanks for raising this issue. I've not come across it before.

I'm not sure what the best solution is. The sierra.txt book also contains non-ascii characters. Are you suggesting just removing non-ascii characters from the book text? 

Given this hasn't cropped up on Ubuntu/Mint/Scientific Linux (and I guess Windows and OSX too - I think @lexnederbragt uses a Mac), perhaps putting the fix in the `guide.md` would be the best place for it?

**Comment by bast** [comment]
Gerard, I agree with your recommendation. It seems my setup is exotic. I don't think we should modify the chapter text, I was more thinking of replacing the "difficult" ones. But now I agree that editing `guide.md` is the way to go. I will submit a PR.
